import { useEffect, useState } from "react";
import { backend } from "../lib/backend";
import type { Project } from "../types";

type Entry={name:string;relativePath:string;directory:boolean;modified:boolean};
type OpenFile={path:string;content:string;sha256:string};
export function FilesView({project}:{project?:Project}){
  const [path,setPath]=useState("");const [entries,setEntries]=useState<Entry[]>([]);const [file,setFile]=useState<OpenFile>();const [draft,setDraft]=useState("");const [editing,setEditing]=useState(false);const [review,setReview]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(project)backend.listDirectory(project.id,path).then(setEntries).catch(e=>setError(String(e)))},[project,path]);
  if(!project)return <Empty name="FILES"/>;
  const openFile=async(relativePath:string)=>{const r=await backend.readFile(project.id,relativePath);setFile({path:relativePath,content:r.content,sha256:r.sha256});setDraft(r.content);setEditing(false)};
  const save=async()=>{if(!file)return;try{const r=await backend.writeFile(project.id,file.path,draft,file.sha256);setFile({path:file.path,content:r.content,sha256:r.sha256});setEditing(false);setReview(false);setError("")}catch(e){setError(String(e));setReview(false)}};
  return <section className="tool-view"><header><span>LOCAL VIEW · AUTHORIZED ROOT ONLY</span><h2>FILES</h2><code>{project.root}/{path}</code></header><div className="file-workspace"><aside>{path&&<button onClick={()=>setPath(path.split("/").slice(0,-1).join("/"))}>..</button>}{entries.map(e=><button key={e.relativePath} onClick={()=>e.directory?setPath(e.relativePath):openFile(e.relativePath)}><i>{e.directory?"◇":"·"}</i>{e.name}</button>)}</aside><main>{file?<><div className="code-head">{file.path}<button onClick={()=>setEditing(!editing)}>{editing?"CANCEL EDIT":"EDIT"}</button></div>{editing?<><textarea className="code-editor" value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/><button className="review-edit" onClick={()=>setReview(true)} disabled={draft===file.content}>REVIEW CHANGE</button></>:<pre className="code-view">{file.content.split("\n").map((line,i)=><div key={i}><span>{i+1}</span>{line}</div>)}</pre>}</>:<p>Select a readable, non-secret source file.</p>}</main></div>{error&&<p className="notice error">{error}</p>}{review&&file&&<div className="approval-overlay"><section><span>LEVEL 2 · PROJECT MODIFICATION</span><h3>WHAT WILL HAPPEN</h3><p>Replace the reviewed contents of <code>{file.path}</code> using an atomic, hash-checked write.</p><h3>FILES AFFECTED</h3><code>{project.root}/{file.path}</code><h3>CAN IT BE UNDONE?</h3><p>Yes, by restoring the previous content. The operation stops if Git reports existing changes in this target.</p><div><button onClick={()=>setReview(false)}>CANCEL</button><button className="primary" onClick={save}>APPROVE EDIT</button></div></section></div>}</section>
}

export function GitView({project}:{project?:Project}){const [status,setStatus]=useState<{branch:string;modified:string[];staged:string[];untracked:string[]}>();const [diff,setDiff]=useState("");const [error,setError]=useState("");useEffect(()=>{if(project)backend.gitStatus(project.id).then(setStatus).catch(e=>setError(String(e)))},[project]);if(!project)return <Empty name="GIT"/>;return <section className="tool-view"><header><span>READ-ONLY REPOSITORY INSPECTION</span><h2>GIT</h2></header>{status&&<div className="git-summary"><section><span>BRANCH</span><strong>{status.branch}</strong></section><section><span>MODIFIED</span><strong>{status.modified.length}</strong></section><section><span>STAGED</span><strong>{status.staged.length}</strong></section><section><span>UNTRACKED</span><strong>{status.untracked.length}</strong></section></div>}<button className="primary" onClick={()=>backend.gitDiff(project.id).then(setDiff).catch(e=>setError(String(e)))}>VIEW DIFF</button>{diff&&<pre className="diff-view">{diff}</pre>}{error&&<p className="notice error">{error}</p>}</section>}

export function TerminalView({project}:{project?:Project}){const [result,setResult]=useState<{stdout:string;stderr:string;exitCode:number;durationMs:number}>();const [running,setRunning]=useState("");if(!project)return <Empty name="TERMINAL"/>;const run=async(script:string)=>{setRunning(script);try{setResult(await backend.runCommand(project.id,"npm",["run",script]))}finally{setRunning("")}};return <section className="tool-view"><header><span>CONTROLLED COMMAND RUNNER</span><h2>TERMINAL</h2><code>cwd: {project.root}</code></header><p className="tool-note">No arbitrary shell is exposed. Commands run as argument arrays with a sanitized environment, timeout, and project-scoped working directory.</p><div className="command-actions"><button onClick={()=>run("test")}>RUN TESTS</button><button onClick={()=>run("lint")}>RUN LINT</button><button onClick={()=>run("build")}>RUN BUILD</button></div>{running&&<p>Running npm run {running}…</p>}{result&&<section className="terminal-result"><header><b>EXIT {result.exitCode}</b><span>{result.durationMs} ms</span></header><pre>{result.stdout}</pre>{result.stderr&&<pre className="stderr">{result.stderr}</pre>}</section>}</section>}

export function SearchView({project}:{project?:Project}){const [query,setQuery]=useState("");const [results,setResults]=useState<Array<{relativePath:string;line:number;preview:string}>>([]);const [error,setError]=useState("");if(!project)return <Empty name="SEARCH"/>;return <section className="tool-view"><header><span>LOCAL CONTENT SEARCH · SECRET FILES EXCLUDED</span><h2>SEARCH</h2></header><form className="search-box" onSubmit={async e=>{e.preventDefault();try{setResults(await backend.searchProject(project.id,query));setError("")}catch(e){setError(String(e))}}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search authorized project"/><button>SEARCH</button></form><div className="search-results">{results.map((r,i)=><div key={`${r.relativePath}:${r.line}:${i}`}><code>{r.relativePath}:{r.line}</code><pre>{r.preview}</pre></div>)}</div>{error&&<p className="notice error">{error}</p>}</section>}

function Empty({name}:{name:string}){return <section className="tool-view"><header><span>AUTHORIZED PROJECT ONLY</span><h2>{name}</h2></header><div className="empty-state">Authorize and select a project to use {name.toLowerCase()}.</div></section>}
