import { open } from "@tauri-apps/plugin-dialog";
import { useEffect, useState } from "react";
import { backend } from "../lib/backend";
import type { ActionEntry, Memory, Project, Task } from "../types";

export function ProjectsView({ projects, onChange }: { projects: Project[]; onChange: () => Promise<void> }) {
  const [candidate, setCandidate] = useState<{ canonicalRoot: string; name: string; isGit: boolean }>();
  const [cloud, setCloud] = useState(false); const [error, setError] = useState("");
  const choose = async () => { try { const selected = await open({ directory: true, multiple: false, title: "Authorize a project folder" }); if (typeof selected === "string") setCandidate(await backend.previewProject(selected)); } catch (e) { setError(String(e)); } };
  const approve = async () => { if (!candidate) return; await backend.authorizeProject(candidate.canonicalRoot, cloud); setCandidate(undefined); setCloud(false); await onChange(); };
  return <View title="AUTHORIZED PROJECTS" kicker="FOLDER-SPECIFIC ACCESS">
    <button className="primary" onClick={choose}>ADD PROJECT</button>{error && <p className="notice error">{error}</p>}
    {candidate && <section className="approval-card"><span>PROJECT ACCESS</span><h3>{candidate.name}</h3><code>{candidate.canonicalRoot}</code><p>JARVIS may read and search files, and run approved developer commands only inside this folder.</p><label><input type="checkbox" checked={cloud} onChange={e => setCloud(e.target.checked)}/> Allow minimum relevant project code to be sent to Groq when required</label><div><button onClick={() => setCandidate(undefined)}>CANCEL</button><button className="primary" onClick={approve}>AUTHORIZE PROJECT</button></div></section>}
    <div className="card-grid">{projects.map(project => <section className="data-card" key={project.id}><span>AUTHORIZED ROOT</span><h3>{project.name}</h3><code>{project.root}</code><p>Cloud code context: {project.cloudCodeAllowed ? "Allowed" : "Blocked"}</p><button className="outline-danger" onClick={async () => { await backend.revokeProject(project.id); await onChange(); }}>REMOVE ACCESS</button></section>)}{projects.length === 0 && <Empty>No project directories are authorized.</Empty>}</div>
  </View>;
}

export function PrivacyView({ projects, mic, wake, onRefresh }: { projects: Project[]; mic: string; wake: string; onRefresh: () => Promise<void> }) {
  return <View title="PRIVACY & PERMISSIONS" kicker="OWNER CONTROL">
    <div className="settings-grid"><StatusCard title="MICROPHONE" value={mic} /><StatusCard title="WAKE WORD" value={wake} /><StatusCard title="FULL DISK ACCESS" value="NOT REQUIRED" /><StatusCard title="ACCESSIBILITY" value="NOT REQUIRED" /><StatusCard title="SCREEN RECORDING" value="NOT REQUIRED" /><StatusCard title="CAMERA" value="NOT REQUIRED" /></div>
    <h3 className="section-title">AUTHORIZED PROJECTS</h3>{projects.map(p => <div className="permission-row" key={p.id}><span><b>{p.name}</b><code>{p.root}</code></span><button className="outline-danger" onClick={async () => { await backend.revokeProject(p.id); await onRefresh(); }}>REVOKE</button></div>)}{projects.length === 0 && <Empty>No project access has been granted.</Empty>}
    <h3 className="section-title">NETWORK SERVICES</h3><p className="privacy-copy">Only Groq inference/STT and Fish Audio TTS are used when their features are explicitly invoked. Ambient wake-word audio remains local and is never archived.</p>
  </View>;
}

export function SettingsView({ onRefresh }: { onRefresh: () => Promise<void> }) {
  const [groq, setGroq] = useState(""); const [fish, setFish] = useState(""); const [voiceId, setVoiceId] = useState("");
  const [status, setStatus] = useState<{ groq?: string; fishAudio?: string }>({}); const [note, setNote] = useState(""); const [resetStep, setResetStep] = useState(0); const [startAtLogin,setStartAtLogin]=useState(false);
  useEffect(() => { backend.credentialStatus().then(setStatus).catch(() => undefined); backend.getStartAtLogin().then(setStartAtLogin).catch(() => undefined); }, []);
  const save = async (provider: "groq" | "fish_audio", value: string) => { if (!value.trim()) return; const masked = await backend.saveCredential(provider, value.trim()); setStatus(s => ({ ...s, [provider === "groq" ? "groq" : "fishAudio"]: masked })); provider === "groq" ? setGroq("") : setFish(""); setNote("Credential stored in this app's macOS Keychain record."); await onRefresh(); };
  return <View title="SETTINGS" kicker="LOCAL CONFIGURATION"><section className="settings-section"><h3>CREDENTIALS</h3><p>Keys are sent directly to their named provider from the native backend and are never exposed to frontend JavaScript after storage.</p><CredentialRow name="Groq" masked={status.groq} value={groq} onValue={setGroq} onSave={() => save("groq", groq)} onRemove={async () => { await backend.removeCredential("groq"); setStatus(s => ({ ...s, groq: undefined })); await onRefresh(); }}/><CredentialRow name="Fish Audio" masked={status.fishAudio} value={fish} onValue={setFish} onSave={() => save("fish_audio", fish)} onRemove={async () => { await backend.removeCredential("fish_audio"); setStatus(s => ({ ...s, fishAudio: undefined })); await onRefresh(); }}/>{note && <p className="notice">{note}</p>}<div className="credential"><label className="field"><span>FISH AUDIO VOICE / REFERENCE ID</span><input value={voiceId} onChange={e => setVoiceId(e.target.value)} placeholder="Configure a voice ID from Fish Audio" /></label><button className="primary" onClick={async()=>{await backend.setFishVoiceId(voiceId);setNote("Fish Audio voice ID saved locally.")}}>SAVE</button></div></section><section className="settings-section"><h3>BACKGROUND MODE</h3><label className="toggle-row"><span><b>START JARVIS AT LOGIN</b><small>Off by default. Keeps the menu-bar helper available after you enable it.</small></span><input type="checkbox" checked={startAtLogin} onChange={async e=>setStartAtLogin(await backend.setStartAtLogin(e.target.checked))}/></label></section>
    <section className="settings-section danger-zone"><h3>RESET JARVIS DATA</h3><p>Removes conversations, project metadata, memory, tasks, and permission records. Actual project folders are never deleted.</p>{resetStep === 0 ? <button className="outline-danger" onClick={() => setResetStep(1)}>REVIEW RESET</button> : resetStep === 1 ? <div className="reset-confirm"><p><b>WHAT WILL HAPPEN:</b> JARVIS local records will be cleared.<br/><b>AFFECTED:</b> conversations, tasks, memory, metadata, permissions.<br/><b>CAN IT BE UNDONE?</b> No. Project files are unaffected.</p><button onClick={() => setResetStep(0)}>CANCEL</button><button className="outline-danger" onClick={() => setResetStep(2)}>I UNDERSTAND</button></div> : <div className="reset-confirm"><p>Second confirmation. This button must be clicked manually.</p><button onClick={() => setResetStep(0)}>CANCEL</button><button className="outline-danger" onClick={async () => { await backend.resetDataConfirmed(); setResetStep(0); await onRefresh(); }}>RESET JARVIS DATA</button></div>}</section>
  </View>;
}

export function TasksView({ tasks, projectId, onRefresh }: { tasks: Task[]; projectId?: string; onRefresh: () => Promise<void> }) { const [title,setTitle]=useState("");return <View title="TASKS" kicker="LOCAL PROJECT WORK"><div className="inline-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New task title"/><button className="primary" onClick={async()=>{if(!title.trim())return;await backend.addTask({title,projectId,description:"",status:"TODO",priority:"MEDIUM"});setTitle("");await onRefresh()}}>ADD TASK</button></div><div className="card-grid">{tasks.map(t => <section className="data-card" key={t.id}><span>{t.priority} PRIORITY</span><h3>{t.title}</h3><p>{t.description}</p><select value={t.status} onChange={async e=>{await backend.updateTaskStatus(t.id,e.target.value as Task["status"]);await onRefresh()}}><option>TODO</option><option>IN PROGRESS</option><option>BLOCKED</option><option>DONE</option></select></section>)}{tasks.length === 0 && <Empty>No local tasks.</Empty>}</div></View>; }
export function MemoryView({ memories, projectId, onRefresh }: { memories: Memory[]; projectId?: string; onRefresh: () => Promise<void> }) { const [content,setContent]=useState("");const [category,setCategory]=useState<Memory["category"]>("PROJECT FACT");return <View title="MEMORY" kicker="INSPECTABLE · EDITABLE · LOCAL"><div className="inline-create"><select value={category} onChange={e=>setCategory(e.target.value as Memory["category"])}><option>PROJECT FACT</option><option>PREFERENCE</option><option>DECISION</option><option>CONSTRAINT</option><option>TODO</option></select><input value={content} onChange={e=>setContent(e.target.value)} placeholder="Store a non-sensitive project memory"/><button className="primary" onClick={async()=>{if(!content.trim())return;await backend.addMemory({projectId,category,content});setContent("");await onRefresh()}}>SAVE</button></div><div className="card-grid">{memories.map(m => <section className="data-card" key={m.id}><span>{m.category}</span><p>{m.content}</p><button onClick={async()=>{await backend.deleteMemory(m.id);await onRefresh()}}>REMOVE</button></section>)}{memories.length === 0 && <Empty>No project facts, preferences, decisions, constraints, or TODOs stored.</Empty>}</div></View>; }
export function ActivityView({ actions }: { actions: ActionEntry[] }) { return <View title="ACTIVITY" kicker="REDACTED AUDIT TRAIL"><div className="activity-table">{actions.map(a => <div key={a.id}><time>{new Date(a.timestamp).toLocaleString()}</time><b>{a.actor}</b><span>{a.actionType}</span><code>{a.target}</code><em className={a.success ? "good" : "bad"}>{a.result}</em></div>)}{actions.length === 0 && <Empty>No actions logged this session.</Empty>}</div></View>; }

export function PlaceholderView({ name }: { name: string }) { return <View title={name.toUpperCase()} kicker="AUTHORIZED PROJECT ONLY"><Empty>Authorize and select a project to use {name.toLowerCase()} tools.</Empty></View>; }

function View({ title, kicker, children }: { title: string; kicker: string; children: React.ReactNode }) { return <section className="view"><header className="view-title"><span>{kicker}</span><h2>{title}</h2></header>{children}</section>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="empty-state">{children}</div>; }
function StatusCard({ title, value }: { title: string; value: string }) { return <section className="status-card"><span>{title}</span><strong>{value}</strong></section>; }
function CredentialRow({ name, masked, value, onValue, onSave, onRemove }: { name: string; masked?: string; value: string; onValue: (s: string) => void; onSave: () => void; onRemove: () => void }) { return <div className="credential"><label className="field"><span>{name.toUpperCase()}</span><input type="password" autoComplete="off" value={value} onChange={e => onValue(e.target.value)} placeholder={masked ?? "Not configured"}/></label><button className="primary" onClick={onSave}>SAVE</button>{masked && <><code>{masked}</code><button onClick={onRemove}>REMOVE</button></>}</div>; }
