import { useCallback, useEffect, useRef, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import { Command, LockKeyhole, Radio, WifiOff } from "lucide-react";
import { backend } from "./lib/backend";
import { useJarvis } from "./store";
import { Sidebar } from "./components/Sidebar";
import { CoreHud } from "./components/CoreHud";
import { StatusPanel } from "./components/StatusPanel";
import { CommandBar } from "./components/CommandBar";
import { Conversation } from "./components/Conversation";
import { ActivityView, MemoryView, PlaceholderView, PrivacyView, ProjectsView, SettingsView, TasksView } from "./components/Views";
import { Onboarding } from "./components/Onboarding";
import { FilesView, GitView, SearchView, TerminalView } from "./components/ToolViews";
import type { JarvisState } from "./types";

export default function App() {
  const store = useJarvis(); const set = useJarvis(s => s.set); const hydrate = useJarvis(s => s.hydrate);
  const [clock, setClock] = useState(new Date());
  const speech = useRef<HTMLAudioElement | null>(null);
  const refresh = useCallback(async () => { try { const data = await backend.bootstrap(); hydrate({ ...data, state: data.locked ? "LOCKED" : data.health.wakeWord === "READY" ? "WAKE WORD READY" : "IDLE" }); } catch (e) { set({ ready: true, error: String(e) }); } }, [hydrate, set]);
  useEffect(() => { refresh(); const timer = window.setInterval(() => setClock(new Date()), 1000); return () => clearInterval(timer); }, [refresh]);
  useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); set({ commandPalette: !useJarvis.getState().commandPalette }); } if ((e.metaKey || e.ctrlKey) && e.shiftKey && e.key === ".") backend.emergencyStop().then(refresh); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [refresh, set]);
  useEffect(()=>{const unlisteners: Array<()=>void>=[];(async()=>{unlisteners.push(await listen<{state:JarvisState;message?:string}>("jarvis://voice-state",event=>set({state:event.payload.state,error:event.payload.message})));unlisteners.push(await listen("jarvis://assistant-message",()=>refresh()));unlisteners.push(await listen<{mime:string;base64:string}>("jarvis://speech-audio",event=>{speech.current?.pause();speech.current=new Audio(`data:${event.payload.mime};base64,${event.payload.base64}`);speech.current.play().catch(e=>set({error:String(e)}));}));})();return()=>unlisteners.forEach(fn=>fn())},[refresh,set]);
  if (!store.ready) return <div className="boot"><CoreHud state="IDLE"/><span>INITIALIZING SECURITY BOUNDARY</span></div>;
  if (store.firstRun && !sessionStorage.getItem("jarvis-onboarding-seen")) return <Onboarding onSettings={() => { sessionStorage.setItem("jarvis-onboarding-seen", "1"); set({ activeView: "Settings" }); }} onProjects={() => { sessionStorage.setItem("jarvis-onboarding-seen", "1"); set({ activeView: "Projects" }); }} onComplete={() => { sessionStorage.setItem("jarvis-onboarding-seen", "1"); set({ firstRun: false }); }} />;
  const project = store.projects.find(p => p.id === store.activeProjectId);
  const send = async (content: string) => { set({ state: "THINKING", messages: [...store.messages, { id: crypto.randomUUID(), role: "user", content, createdAt: new Date().toISOString() }] }); try { const response = await backend.sendMessage(project?.id ?? null, content); set({ messages: [...useJarvis.getState().messages, response], state: "SUCCESS" }); window.setTimeout(() => set({ state: store.health.wakeWord === "READY" ? "WAKE WORD READY" : "IDLE" }), 900); } catch (e) { set({ state: "ERROR", error: String(e) }); } };
  const body = store.activeView === "Core" ? <><div className="core-stage"><CoreHud state={store.state}/><div className="core-readout left"><span>SECURITY</span><strong>DENY BY DEFAULT</strong></div><div className="core-readout right"><span>AUTHORIZED ROOTS</span><strong>{store.projects.length}</strong></div></div><Conversation messages={store.messages}/></> : store.activeView === "Projects" ? <ProjectsView projects={store.projects} onChange={refresh}/> : store.activeView === "Privacy" ? <PrivacyView projects={store.projects} mic={store.health.microphone} wake={store.health.wakeWord} onRefresh={refresh}/> : store.activeView === "Settings" ? <SettingsView onRefresh={refresh}/> : store.activeView === "Tasks" ? <TasksView tasks={store.tasks} projectId={project?.id} onRefresh={refresh}/> : store.activeView === "Memory" ? <MemoryView memories={store.memories} projectId={project?.id} onRefresh={refresh}/> : store.activeView === "Activity" ? <ActivityView actions={store.actions}/> : store.activeView === "Files" ? <FilesView project={project}/> : store.activeView === "Search" ? <SearchView project={project}/> : store.activeView === "Git" ? <GitView project={project}/> : store.activeView === "Terminal" ? <TerminalView project={project}/> : <PlaceholderView name={store.activeView}/>;
  return <div className={`app ${store.locked ? "is-locked" : ""}`}>
    <header className="topbar"><button className="brand" onClick={() => set({ activeView: "Core" })}><span className="brand-glyph">J</span><span><b>JARVIS</b><small>DKOOs ENGINEERING INTELLIGENCE</small></span></button><div className="top-project"><span>ACTIVE PROJECT</span><strong>{project?.name ?? "NO ACCESS GRANTED"}</strong></div><div className="top-status"><span className={`status-light ${store.locked ? "warning" : ""}`}/><span>CORE</span><b>{store.health.core}</b></div><div className="top-privacy"><LockKeyhole size={14}/><span>PRIVACY</span><b>{store.locked ? "LOCKED" : "ENFORCED"}</b></div><time>{clock.toLocaleTimeString([], { hour12: false })}<small>{clock.toLocaleDateString([], { month: "short", day: "2-digit", year: "numeric" }).toUpperCase()}</small></time></header>
    <div className="workspace"><Sidebar active={store.activeView} onSelect={activeView => set({ activeView })}/><main className="main-content">{store.error && <div className="backend-warning"><WifiOff size={16}/>{store.error}</div>}{body}</main><StatusPanel health={store.health} project={project} actions={store.actions}/></div>
    <CommandBar disabled={store.locked} microphone={store.health.microphone} onSend={send} onMic={async () => { await backend.setVoiceListening(store.health.microphone === "OFF"); await refresh(); }} onStop={async () => { speech.current?.pause(); await backend.emergencyStop(); await refresh(); }} onLock={async () => { await backend.setLocked(!store.locked); await refresh(); }}/>
    {store.locked && <div className="lock-overlay"><LockKeyhole/><span>JARVIS LOCKED</span><p>Filesystem, commands, microphone, and network requests are disabled.</p><button onClick={async () => { await backend.setLocked(false); await refresh(); }}>MANUAL UNLOCK</button></div>}
    {store.commandPalette && <div className="palette-backdrop" onClick={() => set({ commandPalette: false })}><section className="palette" onClick={e => e.stopPropagation()}><header><Command/>COMMAND PALETTE <kbd>ESC</kbd></header>{["Switch Project", "Add Project", "Search Files", "View Git Diff", "Run Tests", "Run Build", "View Activity", "Toggle Wake Word", "Lock JARVIS", "Settings"].map(cmd => <button key={cmd} onClick={() => { const map: Record<string,string> = { "Add Project":"Projects", "Search Files":"Search", "View Git Diff":"Git", "View Activity":"Activity", "Settings":"Settings" }; set({ activeView: map[cmd] ?? "Core", commandPalette: false }); }}><Radio size={13}/>{cmd}</button>)}</section></div>}
  </div>;
}
